hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

# config for Channel
channel:
  enable: True
  num_nodes: 1
  distributed: False

actor_rollout_ref:
  rollout:
    agent:
      agent_loop_manager_class: verl.experimental.channel.agent_loop.AgentLoopManager
